spring.application.name=candidate_recruitment_tacker
server.port=5000
spring.datasource.url=jdbc:postgresql://localhost:5432/RecruitmentTracker_DB
#for docker initiation
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/RecruitmentTracker_DB
spring.datasource.username=postgres
spring.datasource.password=your_db_password

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Corrected Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc
spring.session.jdbc.platform=postgresql